name: smart_pa_news
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  bubble_tab_indicator: ^0.1.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^3.0.7
  http: ^0.13.5
  provider: ^6.0.4
  shared_preferences: ^2.0.8
  flutter_appauth: ^4.2.1
  flutter_dotenv: ^5.0.2
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/envs/
